blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView
from django.conf.urls import url,include
from . import views

app_name = 'main'

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-detail'),
    url(r'^(?P<pk>[-\w]+)/$', views.add_comment, name='add_comment')
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    slug = models.SlugField(max_length=240)
    date_posted = models.DateTimeField(default=timezone.now)
    topic_image = models.ImageField(upload_to='profile_image', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Post"

    def __str__(self):
        return self.title


class Comments(models.Model):
    user_comments = models.TextField(max_length=250)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_key = models.ForeignKey(Post, related_name='comments', default=1, verbose_name="Post",
                                           on_delete=models.SET_DEFAULT)

    class Meta:
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.user_comments

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from blog.models import Comments


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('author', 'user_comments',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comments
from django.views.generic import ListView, DetailView, CreateView
from users.forms import CommentForm


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']


class PostDetailView(DetailView):
    model = Post


class PostCreateView(CreateView):
    model = Comments
    fields = [' user_comments',]


def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            user_comments = form.save(commit=False)
            user_comments.post = post
            user_comments.save()
            return redirect('main:add_comment', pk=post.id)
    else:
        form = CommentForm()
    template = 'blog/add_comment.html'
    context = {'form':form}
    return render(request, template, context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog/templates/blog/add_comment.html
{% block content %}
<H1>Add New Comment</H1>
    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type ='submit'>Submit</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/profile"><font color="black" size="40">share.it</font>></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'main:blog-home' %}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>


      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/comment_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>
<body class="register-body">
{% include 'blog/header.html' %}
{% block content %}
    <div class="container row">
        <div class="columns is-mobile">
            <div class="column is-half is-offset-one-quarter">
                <div class="content"><h2>Add Comment</h2></div>
                 <form method="post" class="col s12 m8 l6 offset-l3 offset-m2 form-box center-align">
                                <i class="large material-icons indigo-text text-accent-3 form-hero-icon">person_outline</i>
                    {% csrf_token %}
                    {% for non_field_error in form.non_field_errors %}
                        <p class="help is-danger">{{ non_field_error }}</p>
                    {% endfor %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.html_name }}</label>
                            {{ field }}
                        {% for error in field.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                        </div>
                    {% endfor %}
                        <button class="btn btn-large btn-register waves-effect waves-light indigo accent-3" type="submit" name="action">Register
                        <i class="material-icons right">Comment</i>
                        </button>
                 </form>
            </div>
        </div>
    </div>
{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
            $(document).ready(function(){
    $('.sidenav').sidenav();
    $('.collapsible').collapsible();
    $('input#input_text, textarea#textarea2').characterCounter();
    $('.dropdown-trigger').dropdown();
  });
</script>

<script>
    $('.js-captcha-refresh').click(function(){
    $form = $(this).parents('form');

    $.getJSON($(this).data('url'), {}, function(json) {
        // This should update your captcha image src and captcha hidden input
    });

    return false;
});
</script>
</body>
</html>

blog/templates/blog/header.html
{% load static %}
<head>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="{% static 'css/materialize.css' %}">

  <!-- Compiled and minified JavaScript -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>

  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <script>
    (function($){
    $(function(){

      $('.sidenav').sidenav();

    }); // end of document ready
  })(jQuery); // end of jQuery name space
  </script>
</head>
<body>

{% include "blog/includes/navbar.html" %}
{% include "blog/includes/messages.html" %}

  <!-- <div class="container"> -->
    {% block content %}
    {% endblock %}
  <!-- </div> -->


    <ul id="slide-out" class="sidenav">
      <li><div class="user-view">
        <div class="background">
          <img src="{% static 'img/office.jpg' %}">
        </div>
        <a href="#"><img class="circle" src="{{ user.profile.image.url }}"></a>
        <a href="#"><span class="white-text name">{{ user.username }}</span></a>
        <a href="#"><span class="white-text email">{{ user.email }}</span></a>
      </div></li>
      <li><a class="waves-effect" href="/profile"><i class="material-icons">settings</i>Settings</a></li>
      <li><div class="divider"></div></li>
      <li><a class="waves-effect" href="/logout"><i class="material-icons">dashboard</i>Logout</a></li>
    </ul>
</body>

<!-- <script src="{% static 'tinymce/js/prism.js' %}"></script> -->

blog/templates/blog/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="style.css">

     {% load static %}
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  {% include 'blog/header.html' %}
    <!--NAVBAR------------------------------------------------------------------------------------------------------>

    <!--PAGE CONTENT-CONTAINER------------------------------------------------------------------------------------------------------>
    <div class="container">
    <!--TEXT-HEADER------------------------------------------------------------------------------------------------------>
        <div class="row bottom-border">
            <div class="col s12 m12 l12">
                <h3 class="section-header">Categories</h3>
            </div>
        </div>
    <!--SINGLE ROW OF TOPICS------------------------------------------------------------------------------------------------------>
        <div class="row">
    <!--ONE OF 3 ROWS------------------------------------------------------------------------------------------------------>
          <!-- https://youtu.be/LDU_Txk06tM -->
            {% for post in posts %}
            <div class="col s12 m6 l4">
                <h4 class="center"><a href="{% url 'main:post-detail' post.id %}">{{ post.title }} </a></h4>
                <ul class = "collapsible popout" data-collapsible = "accordion">
                    <li>

                        <div class = "collapsible-header">
                            <div class="row">
                                <div class="col s12 m12 l12 post-author"><a class="">{{ post.author }} </a> {{ post.date_posted|date:"F d, Y" }}</div>
                                 <div class="col s12 m12 l12">{{ post.content }}</div>
                            </div>
                        </div>
                        <div class = "collapsible-body">
                            <p class="bottom-border">Comment Section</p>
                            <ul class = "collection">

                                 {% for com in post.comments.all%}
                                    <li class = "collection-item"><div class="post-author"> <font size="4"> {{ com.author }}</font> posted x {{ com.date_posted|date:"F d, Y" }}</div>
                                         <br>
                                         <font size="4" > {{ com }} </font>
                                 {% endfor %}
                                </li>
                                <li class = "collection-item">

                                </li>
                            </ul>
                        </div>
                    </li>
                    <li>

                        <div class = "collapsible-header">
                            <div class="card">
                                <div class="card-image" >
                                    <img src="{{ post.topic_image.url }}" width="90">
                                </div>
                                <div class="card-content">
                                    <p class=""></p>
                                </div>
                            </div>
                        </div>

                    </li>
                </ul>
            </div>
            {% endfor %}
        </div>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
     $(document).ready(function(){
    $('.sidenav').sidenav();
    $('.collapsible').collapsible();
    $('input#input_text, textarea#textarea2').characterCounter();
    $(".dropdown-trigger").dropdown();
  });
</script>
</body>
</html>

blog/templates/blog/includes/add_comment_to_post.html
{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blog/templates/blog/includes/messages.html
{% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'info'%}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
            {% elif message.tags == 'warning'%}
                <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}

blog/templates/blog/includes/navbar.html
<!--NAVBAR-MAIN------------------------------------------------------------------------------------------------------>
    <nav class="nav-extended indigo accent-3">
        <div class="nav-wrapper container">
            <a href="/" class="brand-logo">share.it</a>
            <ul class="right">
                    {% if user.is_authenticated %}
                        <li><a class="sidenav-trigger" href="#!" data-target="slide-out">{{ user.username }} - Show Profile<i class="material-icons right">menu</i></a></li>
                    {% else %}
                        <li class="hide-on-small-only"><a href="/register">Register</a></li>
                        <li class="hide-on-small-only"><a href="/login">Login</a></li>
             {% endif %}
            </ul>
        </div>
    <!--NAVBAR-SECONDARY------------------------------------------------------------------------------------------------------>
        <!-- CATEGORY NAVBAR
        <div class="nav-content indigo accent-2">
            <div class="container">
                <ul class="tabs tabs-transparent valign-wrapper">
                    <li><a class="btn-floating btn waves-effect waves-light red"><img src="https://images.pexels.com/photos/2037796/pexels-photo-2037796.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt=""></a></li>
                    <li><a class="btn-floating btn waves-effect waves-light red"><img src="https://images.pexels.com/photos/2037796/pexels-photo-2037796.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt=""></a></li>
                    <li><a class="btn-floating btn waves-effect waves-light red"><img src="https://images.pexels.com/photos/2037796/pexels-photo-2037796.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt=""></a></li>
                    <li><a class="btn-floating btn waves-effect waves-light red"><img src="https://images.pexels.com/photos/2037796/pexels-photo-2037796.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" alt=""></a></li>
                </ul>
            </div>
        </div>
        -->
    </nav>
    <!--NAVBAR-DROPDOWN------------------------------------------------------------------------------------------------------>
    <ul id="dropdown1" class="dropdown-content">
            <li class="hide-on-med-and-up indigo-text text-accent-3"><a href="/login">Login</a></li>
            <li class="hide-on-med-and-up"><a href="/register">Register</a></li>
            <li><a href="#!">one</a></li>
            <li><a href="#!">two</a></li>
            <li class="divider"></li>
            <li><a href="#!">three</a></li>
    </ul>

blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="style.css">

     {% load static %}
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  {% include 'blog/header.html' %}
    <!--NAVBAR------------------------------------------------------------------------------------------------------>

    <!--PAGE CONTENT-CONTAINER------------------------------------------------------------------------------------------------------>
    <div class="container">
    <!--TEXT-HEADER------------------------------------------------------------------------------------------------------>
        <div class="row bottom-border">
            <div class="col s12 m12 l12">
                <h3 class="section-header">Categories</h3>
            </div>
        </div>
    <!--SINGLE ROW OF TOPICS------------------------------------------------------------------------------------------------------>
        <div class="row">
    <!--ONE OF 3 ROWS------------------------------------------------------------------------------------------------------>
          <!-- https://youtu.be/LDU_Txk06tM -->
             <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ object.topic_image.url }}" width="500">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ object.author }}</a>
              <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
          </div>
        </article>
            <a href="{% url 'main:add_comment' pk=object.id %}">Leave A Comment</a>

        </div>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
     $(document).ready(function(){
    $('.sidenav').sidenav();
    $('.collapsible').collapsible();
    $('input#input_text, textarea#textarea2').characterCounter();
    $(".dropdown-trigger").dropdown();
  });
</script>
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>
<body class="register-body">
{% include 'blog/header.html' %}
{% block content %}
    <div class="container row">
        <div class="columns is-mobile">
            <div class="column is-half is-offset-one-quarter">
                <div class="content"><h2>Login</h2></div>
                <form method="post" class="col s12 m8 l6 offset-l3 offset-m2 form-box center-align">
                                <i class="large material-icons indigo-text text-accent-3 form-hero-icon">person_outline</i>
                    {% csrf_token %}
                    {% for non_field_error in form.non_field_errors %}
                        <p class="help is-danger">{{ non_field_error }}</p>
                    {% endfor %}
                    {% for field in form %}
                        <div class="input-field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.html_name }}</label>
                            {{ field }}
                        {% for error in field.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                        </div>
                    {% endfor %}
                        <button class="btn btn-large btn-register waves-effect waves-light indigo accent-3" type="submit" name="action">Login
                        <i class="material-icons right">done</i>
                        </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
         $(document).ready(function(){
    $('.sidenav').sidenav();
    $('.collapsible').collapsible();
    $('input#input_text, textarea#textarea2').characterCounter();
    $('.dropdown-trigger').dropdown();

  });
</script>
</body>
</html>

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'blog-home' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/profile.html
<br>
<br>
<br>
{% extends "blog/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" width="99">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
    </div>
{% endblock content %}

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>
<body class="register-body">
{% include 'blog/header.html' %}
{% block content %}
    <div class="container row">
        <div class="columns is-mobile">
            <div class="column is-half is-offset-one-quarter">
                <div class="content"><h2>Register</h2></div>
                 <form method="post" class="col s12 m8 l6 offset-l3 offset-m2 form-box center-align">
                                <i class="large material-icons indigo-text text-accent-3 form-hero-icon">person_outline</i>
                    {% csrf_token %}
                    {% for non_field_error in form.non_field_errors %}
                        <p class="help is-danger">{{ non_field_error }}</p>
                    {% endfor %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">{{ field.html_name }}</label>
                            {{ field }}
                        {% for error in field.errors %}
                            <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                        </div>
                    {% endfor %}
                        <button class="btn btn-large btn-register waves-effect waves-light indigo accent-3" type="submit" name="action">Register
                        <i class="material-icons right">done</i>
                        </button>
                 </form>
            </div>
        </div>
    </div>
{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
            $(document).ready(function(){
    $('.sidenav').sidenav();
    $('.collapsible').collapsible();
    $('input#input_text, textarea#textarea2').characterCounter();
    $('.dropdown-trigger').dropdown();
  });
</script>

<script>
    $('.js-captcha-refresh').click(function(){
    $form = $(this).parents('form');

    $.getJSON($(this).data('url'), {}, function(json) {
        // This should update your captcha image src and captcha hidden input
    });

    return false;
});
</script>
</body>
</html>